//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chi.SocialNetwork.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialNetworkEntities : DbContext
    {
        public SocialNetworkEntities()
            : base("name=SocialNetworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserPostComment> UserPostComments { get; set; }
        public virtual DbSet<UserPostLike> UserPostLikes { get; set; }
        public virtual DbSet<UserPost> UserPosts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPostCommentLike> UserPostCommentLikes { get; set; }
        public virtual DbSet<UserPostFile> UserPostFiles { get; set; }
    }
}
