//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chi.SocialNetwork.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserPostComments = new HashSet<UserPostComment>();
            this.UserPostLikes = new HashSet<UserPostLike>();
            this.UserPosts = new HashSet<UserPost>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<UserPostComment> UserPostComments { get; set; }
        public virtual ICollection<UserPostLike> UserPostLikes { get; set; }
        public virtual ICollection<UserPost> UserPosts { get; set; }
    }
}
