//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chi.SocialNetwork.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPostCommentLike
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int UserPostComment_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserPostComment UserPostComment { get; set; }
    }
}
